### ISSUE TITLE
Таблица со сведениями о конкурсах

### ISSUE THREAD

**Issue by w3prog** [w3prog/moevmCommon#3]

**Comment by w3prog** [comment]
Предлагаю объединить с конференциями и выставками с такими-же полями.

```
Наименование конференции или выставки
Уровень конференции или выставки
Наименование доклада или экспоната
```

**Comment by zmm** [comment]
Мне кажется можно поле назвать просто Наименование, Уровень, Наименование, а тип мероприятия указать в отдельном поле

**Comment by w3prog** [comment]
Да это логично, но данная таблица мне нужна лишь для одного отчета, она по большей части используется в приложении Романа.
